(() => {
  const $ = selector => document.querySelector(selector), esc = value => String(value || '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
  let user, exams = [], summaries = [], currentView = 'dashboard', selectedPdf = null, savedPdfPath = null, savedPdfName = null;
  const dateFormat = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' });
  const setLogin = async state => { $('#loginView').hidden = state; $('#adminApp').hidden = !state; if (state) { await load(); showView('dashboard'); } };
  const load = async () => { [exams, summaries] = await Promise.all([nexaApi.getExams(), nexaApi.getSummaries()]); populateExams(); renderAdmin(); renderExams(); };
  const showView = view => { currentView = view; ['dashboard','summaries','editor','exams'].forEach(name => { $(`#${name}View`).hidden = name !== view; document.querySelector(`[data-view="${name}"]`)?.classList.toggle('active', name === view); }); const labels = { dashboard:['PAINEL','Visão geral'], summaries:['CONTEÚDO','Meus resumos'], editor:['EDITOR','Criar resumo'], exams:['ORGANIZAÇÃO','Gerenciar provas'] }; $('#pageEyebrow').textContent = labels[view][0]; $('#pageTitle').textContent = labels[view][1]; if (view === 'editor' && !$('#editingId').value) resetEditor(); };
  const examWhen = exam => [exam.examDate ? new Date(`${exam.examDate}T12:00:00`).toLocaleDateString('pt-BR') : '', exam.classTime].filter(Boolean).join(' · ');
  const populateExams = () => { $('#summaryExam').innerHTML = exams.map(exam => `<option value="${exam.id}">${esc(exam.subject)} — ${esc(exam.title)} (${esc(examWhen(exam))})</option>`).join(''); };
  const renderAdmin = () => { const published = summaries.filter(s => s.status === 'published'), drafts = summaries.filter(s => s.status === 'draft'), last = summaries.map(s => s.updatedAt).filter(Boolean).sort().at(-1); $('#totalExams').textContent = exams.length; $('#totalSummaries').textContent = summaries.length; $('#totalPublished').textContent = published.length; $('#totalDrafts').textContent = drafts.length; $('#lastUpdate').textContent = last ? `Último resumo atualizado em ${dateFormat.format(new Date(last))}.` : 'Nenhum resumo criado até agora.'; $('#adminSummaryList').innerHTML = summaries.length ? summaries.map(summary => { const exam = summary.exam || exams.find(item => item.id === summary.examId); return `<tr><td><strong>${esc(summary.title)}</strong></td><td>${esc(exam?.subject)}</td><td>${esc(exam?.title)}<br><small>${esc(exam?.classTime)}</small></td><td><span class="status ${summary.status}">${summary.status === 'published' ? 'Publicado' : 'Rascunho'}</span></td><td>${dateFormat.format(new Date(summary.updatedAt))}</td><td><div class="table-actions"><button data-action="edit" data-id="${summary.id}">Editar</button><button data-action="preview" data-id="${summary.id}">Visualizar</button><button data-action="toggle" data-id="${summary.id}">${summary.status === 'published' ? 'Despublicar' : 'Publicar'}</button><button class="danger" data-action="delete" data-id="${summary.id}">Excluir</button></div></td></tr>`; }).join('') : '<tr><td colspan="6" style="text-align:center;color:#64748b;padding:28px">Você ainda não criou nenhum resumo.</td></tr>'; };
  const renderExams = () => { $('#examAdminList').innerHTML = exams.map(exam => `<article class="exam-admin-card"><strong>${esc(exam.subject)}</strong><span>${esc(exam.title)}</span><small>${esc(examWhen(exam))}</small><div><button data-exam-action="edit" data-id="${exam.id}">Editar</button><button data-exam-action="delete" data-id="${exam.id}" class="danger">Excluir</button></div></article>`).join(''); };
  const resetEditor = () => { $('#summaryForm').reset(); $('#editingId').value = ''; $('#contentEditor').innerHTML = ''; selectedPdf = null; savedPdfPath = null; savedPdfName = null; $('#pdfStatus').textContent = ''; toggleMaterialType(); updatePreview(); };
  const toggleMaterialType = () => { const pdf = $('#summaryType').value === 'pdf'; $('#writtenEditor').hidden = pdf; $('#pdfEditor').hidden = !pdf; };
  const draftData = status => ({ id: $('#editingId').value || undefined, examId: $('#summaryExam').value, title: $('#summaryTitle').value.trim(), introduction: $('#summaryIntro').value.trim(), contentType: $('#summaryType').value, content: $('#contentEditor').innerHTML.trim(), pdfPath: savedPdfPath, pdfName: savedPdfName, authorId: user.id, status });
  const materialPreview = data => data.contentType === 'pdf' ? (data.pdfName ? `<div class="pdf-preview">📄 <strong>${esc(data.pdfName)}</strong><span>Arquivo PDF armazenado no Supabase.</span></div>` : '<p class="preview-empty">Anexe um arquivo PDF para publicar este resumo.</p>') : (data.content || '<p class="preview-empty">Escreva o conteúdo do resumo para ver a pré-visualização.</p>');
  const updatePreview = () => { const data = draftData('draft'), exam = exams.find(item => item.id === data.examId); $('#previewContent').innerHTML = data.title ? `<p class="eyebrow">${esc(exam?.subject)} · ${esc(exam?.classTime)}</p><h1>${esc(data.title)}</h1><p class="meta">${esc(exam?.title)}</p>${data.introduction ? `<p>${esc(data.introduction)}</p>` : ''}${materialPreview(data)}` : '<p class="preview-empty">Preencha o resumo para ver como ele ficará para o aluno.</p>'; };
  async function save(status) { try { let data = draftData(status); if (!data.title) return $('#summaryTitle').focus(); if (data.contentType === 'pdf' && selectedPdf) { const uploaded = await nexaApi.uploadPdf(selectedPdf); data.pdfPath = savedPdfPath = uploaded.path; data.pdfName = savedPdfName = uploaded.name; } if (data.contentType === 'pdf' && !data.pdfPath) throw new Error('Escolha um arquivo PDF antes de salvar.'); await nexaApi.saveSummary(data); await load(); $('#editingId').value = data.id || ''; updatePreview(); if (status === 'published') showView('summaries'); } catch (error) { $('#pdfStatus').textContent = error.message || 'Não foi possível salvar o material.'; } }
  $('#loginForm').onsubmit = async event => { event.preventDefault(); try { await authService.login($('#email').value, $('#password').value); user = await nexaApi.currentUser(); if (user?.role !== 'admin') { await authService.logout(); throw new Error('Este e-mail não possui acesso administrativo.'); } await setLogin(true); } catch (error) { $('#loginError').textContent = error.message || 'Não foi possível entrar.'; } };
  $('#logoutButton').onclick = async () => { await authService.logout(); user = null; setLogin(false); $('#password').value = ''; };
  document.addEventListener('click', async event => { const tab = event.target.closest('[data-view]'); if (tab) showView(tab.dataset.view); if (event.target.matches('.close-dialog')) $('#previewDialog').close(); const action = event.target.closest('[data-action]'); if (action) { const summary = summaries.find(item => item.id === action.dataset.id); if (!summary) return; if (action.dataset.action === 'edit') { $('#editingId').value = summary.id; $('#summaryExam').value = summary.examId; $('#summaryTitle').value = summary.title; $('#summaryIntro').value = summary.introduction; $('#summaryType').value = summary.contentType; $('#contentEditor').innerHTML = summary.content; savedPdfPath = summary.pdfPath; savedPdfName = summary.pdfName; selectedPdf = null; $('#pdfStatus').textContent = savedPdfName ? `PDF salvo: ${savedPdfName}` : ''; toggleMaterialType(); showView('editor'); $('#pageTitle').textContent = 'Editar resumo'; updatePreview(); } if (action.dataset.action === 'preview') { const exam = summary.exam || exams.find(item => item.id === summary.examId); $('#fullPreview').innerHTML = `<p class="eyebrow">${esc(exam?.subject)} · ${esc(exam?.classTime)}</p><h1>${esc(summary.title)}</h1>${materialPreview(summary)}`; $('#previewDialog').showModal(); } if (action.dataset.action === 'toggle') { await nexaApi.saveSummary({ ...summary, status: summary.status === 'published' ? 'draft' : 'published' }); await load(); } if (action.dataset.action === 'delete' && confirm(`Excluir o resumo “${summary.title}”?`)) { await nexaApi.deleteSummary(summary.id); await load(); } } const examAction = event.target.closest('[data-exam-action]'); if (examAction) { const exam = exams.find(item => item.id === examAction.dataset.id); if (examAction.dataset.examAction === 'edit') { $('#examId').value = exam.id; $('#examSubject').value = exam.subject; $('#examTitle').value = exam.title; $('#examClassTime').value = exam.classTime; } if (examAction.dataset.examAction === 'delete') try { await nexaApi.deleteExam(exam.id); await load(); } catch { $('#examMessage').textContent = 'Esta prova possui resumos vinculados e não pode ser removida.'; } } });
  ['input','change'].forEach(type => $('#summaryForm').addEventListener(type, updatePreview)); $('#summaryType').onchange = () => { toggleMaterialType(); updatePreview(); }; $('#pdfFile').onchange = event => { selectedPdf = event.target.files[0] || null; if (selectedPdf) { savedPdfPath = null; savedPdfName = selectedPdf.name; $('#pdfStatus').textContent = `PDF selecionado: ${selectedPdf.name}`; } updatePreview(); }; document.querySelectorAll('.toolbar [data-command]').forEach(button => button.onclick = () => { document.execCommand(button.dataset.command, false, button.dataset.value || null); $('#contentEditor').focus(); updatePreview(); }); $('#calloutButton').onclick = () => { document.execCommand('insertHTML', false, '<div class="callout"><strong>Importante:</strong> Escreva uma informação que o aluno não pode esquecer.</div><p><br></p>'); updatePreview(); }; $('#separatorButton').onclick = () => { document.execCommand('insertHTML', false, '<hr><p><br></p>'); updatePreview(); }; $('#summaryForm').onsubmit = event => { event.preventDefault(); save('published'); }; $('#saveDraft').onclick = () => save('draft'); $('#previewButton').onclick = () => { updatePreview(); $('#fullPreview').innerHTML = $('#previewContent').innerHTML; $('#previewDialog').showModal(); };
  $('#examForm').onsubmit = async event => { event.preventDefault(); try { await nexaApi.saveExam({ id: $('#examId').value || undefined, subject: $('#examSubject').value.trim(), title: $('#examTitle').value.trim(), examDate: $('#examDate').value, classTime: $('#examClassTime').value.trim() }); $('#examForm').reset(); $('#examId').value = ''; $('#examMessage').textContent = 'Prova salva com sucesso.'; await load(); } catch (error) { $('#examMessage').textContent = error.message; } }; $('#clearExam').onclick = () => { $('#examForm').reset(); $('#examId').value = ''; };
  (async () => { user = await nexaApi.currentUser(); if (user?.role === 'admin') setLogin(true); else setLogin(false); })();
  // Mantém a data ao reabrir uma prova existente para edição.
  document.addEventListener('click', event => { const button = event.target.closest('[data-exam-action="edit"]'); if (!button) return; const exam = exams.find(item => item.id === button.dataset.id); if (exam) $('#examDate').value = exam.examDate || ''; });
})();