/* NEXA storageService
   IMPORTANTE: Esta versão utiliza localStorage apenas para desenvolvimento/protótipo.
   Para publicar a NEXA na internet e permitir que os resumos sejam compartilhados entre todos
   os visitantes, será necessário utilizar um backend e um banco de dados.
   Futuro ponto de integração: substitua os métodos deste serviço por chamadas à API segura. */
window.storageService = (() => {
  const KEYS = { exams: 'nexa_exams_v1', summaries: 'nexa_summaries_v1', users: 'nexa_users_v1', session: 'nexa_user_session_v1', ratings:'nexa_ratings_v1', reports:'nexa_reports_v1', quizzes:'nexa_quizzes_v1' };
  const initialExams = [
    { id:'espanhol', subject:'Espanhol', title:'Prova Bimestral de Espanhol', classTime:'2ª aula' },
    { id:'redacao', subject:'Redação', title:'Prova Bimestral de Redação', classTime:'2ª e 3ª aulas' },
    { id:'ingles', subject:'Inglês', title:'Prova Bimestral de Inglês', classTime:'2ª aula' },
    { id:'religioso', subject:'Ensino Religioso', title:'Prova Bimestral de Ensino Religioso', classTime:'3ª aula' },
    { id:'ciencias', subject:'Ciências', title:'Prova Bimestral de Ciências', classTime:'3ª aula' }
  ];
  const read = key => JSON.parse(localStorage.getItem(key) || '[]');
  const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  function ensureSeed(){ if(!localStorage.getItem(KEYS.exams)) write(KEYS.exams, initialExams); if(!localStorage.getItem(KEYS.summaries)) write(KEYS.summaries, []); }
  function getExams(){ ensureSeed(); return read(KEYS.exams); }
  function getSummaries(){ ensureSeed(); return read(KEYS.summaries); }
  function getSummary(id){ return getSummaries().find(item => item.id === id); }
  function saveSummary(summary){ const all=getSummaries(); const index=all.findIndex(item=>item.id===summary.id); if(index >= 0) all[index]=summary; else all.unshift(summary); write(KEYS.summaries,all); return summary; }
  function deleteSummary(id){ write(KEYS.summaries, getSummaries().filter(item=>item.id!==id)); }
  function saveExam(exam){const all=getExams();const index=all.findIndex(item=>item.id===exam.id);if(index>=0)all[index]=exam;else all.push(exam);write(KEYS.exams,all);return exam;}
  function deleteExam(id){const hasSummary=getSummaries().some(summary=>summary.examId===id);if(hasSummary)throw new Error('Esta prova possui resumos vinculados e não pode ser removida.');write(KEYS.exams,getExams().filter(exam=>exam.id!==id));}
  function ratings(){return read(KEYS.ratings);}function ratingStats(summaryId){const list=ratings().filter(r=>r.summaryId===summaryId);return {count:list.length,average:list.length?list.reduce((sum,r)=>sum+r.score,0)/list.length:0};}
  function rate(summaryId,score){const user=currentUser();if(!user)return null;const all=ratings();const index=all.findIndex(r=>r.summaryId===summaryId&&r.userId===user.id);const value={id:index>=0?all[index].id:crypto.randomUUID(),summaryId,userId:user.id,score:Number(score),updatedAt:new Date().toISOString()};if(index>=0)all[index]=value;else all.push(value);write(KEYS.ratings,all);return value;}
  function registerView(summaryId){const stamp=`nexa_view_${summaryId}`;const previous=Number(sessionStorage.getItem(stamp)||0);if(Date.now()-previous<30*60*1000)return false;const summary=getSummary(summaryId);if(!summary)return false;summary.views=(summary.views||0)+1;summary.updatedAt=summary.updatedAt||new Date().toISOString();saveSummary(summary);sessionStorage.setItem(stamp,String(Date.now()));return true;}
  function reports(){return read(KEYS.reports);}function report(summaryId,reason,description){const user=currentUser();if(!user)return null;const summary=getSummary(summaryId);const item={id:crypto.randomUUID(),summaryId,authorId:summary?.authorId||'',reporterId:user.id,reporterName:user.username,reason,description,status:'pending',createdAt:new Date().toISOString()};write(KEYS.reports,[...reports(),item]);return item;}
  function currentUser(){ try{return JSON.parse(localStorage.getItem(KEYS.session)||'null');}catch{return null;} }
  function favoriteKey(){const user=currentUser();return user?`nexa_favorites_${user.id}_v1`:null;}
  function favoriteIds(){const key=favoriteKey();return key?read(key):[];}
  function toggleFavorite(id){const key=favoriteKey();if(!key)return null;const ids=favoriteIds();const next=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];write(key,next);return next.includes(id);}
  return { getExams, getSummaries, getSummary, saveSummary, deleteSummary, saveExam, deleteExam, currentUser, favoriteIds, toggleFavorite, ratingStats, rate, registerView, reports, report, KEYS };
})();

/* Protótipo local: hashes e sessões ficam neste navegador. Em produção, troque por
   backend, cookies seguros, autorização no servidor e banco de dados. */
window.authService=(()=>{
  const users=()=>JSON.parse(localStorage.getItem(storageService.KEYS.users)||'[]');
  const save=items=>localStorage.setItem(storageService.KEYS.users,JSON.stringify(items));
  const hash=async value=>{const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');};
  async function create(username,password){const name=username.trim();if(name.length<3)throw new Error('Use ao menos 3 caracteres no nome.');if(users().some(u=>u.username.toLowerCase()===name.toLowerCase()))throw new Error('Este nome de usuário já existe.');const user={id:crypto.randomUUID(),username:name,passwordHash:await hash(password),createdAt:new Date().toISOString()};save([...users(),user]);return user;}
  async function login(username,password){const user=users().find(u=>u.username.toLowerCase()===username.trim().toLowerCase());if(!user||user.passwordHash!==await hash(password))throw new Error('Nome de usuário ou senha inválidos.');const session={id:user.id,username:user.username,createdAt:user.createdAt};localStorage.setItem(storageService.KEYS.session,JSON.stringify(session));return session;}
  function logout(){localStorage.removeItem(storageService.KEYS.session);}
  return {create,login,logout,users};
})();

(() => {
  if (!document.getElementById('examGrid')) return;
  const $ = selector => document.querySelector(selector);
  const examGrid=$('#examGrid'), summaryList=$('#summaryList'), favoritesList=$('#favoritesList'), search=$('#searchInput'), dialog=$('#readerDialog');
  let activeQuery=''; let subjectQuery=''; let authorQuery=''; let order='recent'; let pdfState=null;
  const escapeHtml=value=>String(value||'').replace(/[&<>'"]/g, char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const examFor=id=>storageService.getExams().find(exam=>exam.id===id);
  const summaryMarkup=summary=>{ const exam=examFor(summary.examId);const excerpt=(summary.introduction||String(summary.content||'').replace(/<[^>]+>/g,'')||'Material preparado para revisão.').slice(0,115);return `<article class="summary-card preview-card"><div class="subject-dot">${escapeHtml(exam.subject[0])}</div><div class="summary-details"><h3>${escapeHtml(summary.title)}</h3><p class="excerpt">${escapeHtml(excerpt)}${excerpt.length>=115?'…':''}</p><p>👤 Autor: <strong>${escapeHtml(summary.authorName||'NEXA')}</strong> · ${escapeHtml(exam.subject)} · ${escapeHtml(exam.classTime)}</p><small>${summary.contentType==='pdf'?'📄 Material em PDF · ':''}${summary.updatedAt?new Date(summary.updatedAt).toLocaleDateString('pt-BR'):''}</small></div><div class="summary-actions"><button class="outline-button favorite-button" data-id="${summary.id}">${storageService.favoriteIds().includes(summary.id)?'★ Favoritado':'☆ Favoritar'}</button><button class="outline-button read-button" data-id="${summary.id}">Abrir resumo →</button></div></article>`; };
  function filteredSummaries(){ const q=activeQuery.trim().toLocaleLowerCase('pt-BR'); const results=storageService.getSummaries().filter(s=>s.status==='published').filter(s=>{const e=examFor(s.examId);const searchable=[s.title,e.subject,e.title,s.authorName,s.introduction,String(s.content||'').replace(/<[^>]+>/g,'')].join(' ').toLocaleLowerCase('pt-BR');return (!q||searchable.includes(q))&&(!subjectQuery||e.subject===subjectQuery)&&(!authorQuery||s.authorId===authorQuery);});return results.sort((a,b)=>order==='popular'?0:new Date(b.updatedAt)-new Date(a.updatedAt)); }
  function render(){ const exams=storageService.getExams(), all=storageService.getSummaries(), published=filteredSummaries(); $('#examCount').textContent=exams.length; $('#publishedCount').textContent=all.filter(s=>s.status==='published').length;const authors=[...new Map(all.filter(s=>s.authorId).map(s=>[s.authorId,s.authorName])).entries()];$('#subjectFilter').innerHTML='<option value="">Todas as matérias</option>'+exams.map(e=>`<option value="${escapeHtml(e.subject)}">${escapeHtml(e.subject)}</option>`).join('');$('#subjectFilter').value=subjectQuery;$('#authorFilter').innerHTML='<option value="">Todos os autores</option>'+authors.map(([id,name])=>`<option value="${id}">${escapeHtml(name)}</option>`).join('');$('#authorFilter').value=authorQuery;
    examGrid.innerHTML=exams.map(exam=>`<article class="exam-card" data-exam="${exam.id}" tabindex="0"><div class="exam-icon">▤</div><p>${escapeHtml(exam.subject)}</p><h3>${escapeHtml(exam.title)}</h3><p>${escapeHtml(exam.classTime)}</p></article>`).join('');
    summaryList.innerHTML=published.length ? published.map(summaryMarkup).join('') : `<div class="empty">${activeQuery?'Nenhum resumo encontrado para esta pesquisa.':'Resumo ainda não publicado.'}</div>`;
    const favoriteSummaries=storageService.getSummaries().filter(s=>s.status==='published'&&storageService.favoriteIds().includes(s.id));
    favoritesList.innerHTML=favoriteSummaries.length?favoriteSummaries.map(summaryMarkup).join(''):'<div class="empty">Você ainda não salvou nenhum resumo.</div>';
    $('#clearSearch').hidden=!activeQuery;
  }
  async function renderPdf(fit=false){if(!pdfState)return;const host=$('#pdfCanvasHost'),page=await pdfState.pdf.getPage(pdfState.page);let base=page.getViewport({scale:1});if(fit)pdfState.scale=Math.max(.65,Math.min(2.2,(host.clientWidth-28)/base.width));const view=page.getViewport({scale:pdfState.scale});const canvas=$('#pdfCanvas');const ctx=canvas.getContext('2d');canvas.width=view.width;canvas.height=view.height;await page.render({canvasContext:ctx,viewport:view}).promise;$('#pdfPageInfo').textContent=`Página ${pdfState.page} / ${pdfState.pdf.numPages}`;$('#pdfZoom').textContent=`${Math.round(pdfState.scale*100)}%`;}
  async function loadPdf(data){const host=$('#pdfCanvasHost');if(!window.pdfjsLib){host.innerHTML='<p>O leitor de PDF precisa de conexão para carregar seus controles. Use o botão Baixar PDF.</p>';return;}try{const pdf=await pdfjsLib.getDocument(data).promise;pdfState={pdf,page:1,scale:1};await renderPdf(true);}catch{host.innerHTML='<p>Não foi possível abrir este PDF.</p>';}}
  function openReader(id){ const s=storageService.getSummary(id); if(!s) return; const e=examFor(s.examId); const pdfContent=s.contentType==='pdf'?s.pdfData?`<div class="pdf-reader"><p>📄 <strong>${escapeHtml(s.pdfName||'Resumo em PDF')}</strong></p><div class="pdf-controls"><button id="pdfPrev">← Página</button><button id="pdfNext">Próxima →</button><button id="pdfMinus">−</button><button id="pdfZoom">100%</button><button id="pdfPlus">+</button><button id="pdfFit">Ajustar</button><button id="pdfFullscreen">Tela cheia</button></div><div id="pdfPageInfo">Carregando PDF…</div><div id="pdfCanvasHost"><canvas id="pdfCanvas"></canvas></div><a class="outline-button" href="${s.pdfData}" download="${escapeHtml(s.pdfName||'resumo-nexa.pdf')}">Baixar PDF</a></div>`:'<p>Arquivo PDF não encontrado neste navegador.</p>':(s.content||'<p>Resumo ainda não publicado.</p>'); $('#readerContent').innerHTML=`<p class="eyebrow">${escapeHtml(e.subject)} · ${escapeHtml(e.classTime)}</p><h1>${escapeHtml(s.title)}</h1><p class="meta">${escapeHtml(e.title)} · Publicado por <strong>${escapeHtml(s.authorName||'NEXA')}</strong></p>${s.introduction?`<p>${escapeHtml(s.introduction)}</p>`:''}<div class="content-body">${pdfContent}</div>`; $('#readerFavorite').dataset.id=id; $('#readerFavorite').textContent=storageService.favoriteIds().includes(id)?'★ Favoritado':'☆ Favoritar'; dialog.showModal();if(s.contentType==='pdf'&&s.pdfData)setTimeout(()=>loadPdf(s.pdfData),80); }
  document.addEventListener('click', event=>{ const read=event.target.closest('.read-button'); const fav=event.target.closest('.favorite-button'); const exam=event.target.closest('.exam-card'); if(read) openReader(read.dataset.id); if(fav){if(storageService.toggleFavorite(fav.dataset.id)===null){location.href='auth.html';return;}render();} if(exam){activeQuery=examFor(exam.dataset.exam).subject;search.value=activeQuery;render();location.hash='resumos';} if(event.target.matches('[data-scroll]')) location.hash=event.target.dataset.scroll; if(event.target.matches('.close-dialog')) dialog.close(); if(event.target.id==='readerFavorite'){if(storageService.toggleFavorite(event.target.dataset.id)===null){location.href='auth.html';return;}event.target.textContent=storageService.favoriteIds().includes(event.target.dataset.id)?'★ Favoritado':'☆ Favoritar';render();} if(event.target.id==='studyMode'){$('.reader').classList.toggle('study');event.target.textContent=$('.reader').classList.contains('study')?'Sair do modo de estudo':'Modo de estudo';} if(event.target.dataset.size){const content=$('#readerContent');const current=parseFloat(getComputedStyle(content).fontSize);content.style.fontSize=`${Math.max(14,Math.min(23,current+(event.target.dataset.size==='larger'?1:-1))) }px`;}if(event.target.id==='pdfPrev'&&pdfState&&pdfState.page>1){pdfState.page--;renderPdf();}if(event.target.id==='pdfNext'&&pdfState&&pdfState.page<pdfState.pdf.numPages){pdfState.page++;renderPdf();}if(event.target.id==='pdfMinus'&&pdfState){pdfState.scale=Math.max(.5,pdfState.scale-.15);renderPdf();}if(event.target.id==='pdfPlus'&&pdfState){pdfState.scale=Math.min(3,pdfState.scale+.15);renderPdf();}if(event.target.id==='pdfFit'&&pdfState)renderPdf(true);if(event.target.id==='pdfFullscreen')$('#pdfCanvasHost')?.requestFullscreen?.();});
  search.addEventListener('input',event=>{activeQuery=event.target.value;render();}); $('#clearSearch').onclick=()=>{activeQuery='';search.value='';render();search.focus();};
  $('#subjectFilter').addEventListener('change',e=>{subjectQuery=e.target.value;render();});$('#authorFilter').addEventListener('change',e=>{authorQuery=e.target.value;render();});$('#orderFilter').addEventListener('change',e=>{order=e.target.value;render();});
  $('.menu-button').onclick=()=>{const nav=$('.main-nav');nav.classList.toggle('open');$('.menu-button').setAttribute('aria-expanded',nav.classList.contains('open'));};
  document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();search.focus();}});const user=storageService.currentUser();const account=$('#accountLink');if(user){account.textContent=`Olá, ${user.username}`;account.href='studio.html';}$('#year').textContent=new Date().getFullYear(); render();
})();