(() => {
  const $ = selector => document.querySelector(selector), esc = value => String(value || '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
  const fmt = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' }); let user, exams = [], summaries = [], pdfFile = null, savedPdfPath = null, savedPdfName = null;
  const own = () => summaries.filter(summary => summary.authorId === user.id);
  const editor = on => { $('#profileView').hidden = on; $('#editorView').hidden = !on; $('#studioTitle').textContent = on ? ($('#editId').value ? 'Editar resumo' : 'Criar resumo') : 'Meu perfil'; };
  const toggle = () => { const pdf = $('#formatSelect').value === 'pdf'; $('#textField').hidden = pdf; $('#pdfField').hidden = !pdf; };
  const render = async () => { [exams, summaries] = await Promise.all([nexaApi.getExams(), nexaApi.getSummaries()]); const mine = own(), published = mine.filter(summary => summary.status === 'published'), favorites = await nexaApi.favoriteIds(); $('#profileName').textContent = user.username; $('#myPublished').textContent = published.length; $('#myFavorites').textContent = favorites.length; $('#createdAt').textContent = fmt.format(new Date(user.createdAt)); $('#examSelect').innerHTML = exams.map(exam => `<option value="${exam.id}">${esc(exam.subject)} — ${esc(exam.title)}</option>`).join(''); $('#mySummaryList').innerHTML = mine.length ? mine.map(summary => { const exam = summary.exam || exams.find(item => item.id === summary.examId); return `<tr><td><strong>${esc(summary.title)}</strong><br><small>${esc(summary.authorName)}</small></td><td>${esc(exam?.subject)}</td><td>${summary.status === 'published' ? 'Publicado' : 'Rascunho'}</td><td>${fmt.format(new Date(summary.updatedAt))}</td><td><div class="table-actions"><button data-action="edit" data-id="${summary.id}">Editar</button><button data-action="delete" data-id="${summary.id}">Excluir</button></div></td></tr>`; }).join('') : '<tr><td colspan="5" style="text-align:center;padding:25px;color:#64748b">Você ainda não publicou resumos.</td></tr>'; };
  const reset = () => { $('#studioForm').reset(); $('#editId').value = ''; pdfFile = null; savedPdfPath = null; savedPdfName = null; $('#studioMessage').textContent = ''; toggle(); };
  async function save(status) { try { const type = $('#formatSelect').value; if (type === 'pdf' && pdfFile) { const uploaded = await nexaApi.uploadPdf(pdfFile); savedPdfPath = uploaded.path; savedPdfName = uploaded.name; } if (type === 'pdf' && !savedPdfPath) throw new Error('Selecione um PDF válido antes de salvar.'); const content = $('#contentInput').value.trim().split('\n').filter(Boolean).map(line => `<p>${esc(line)}</p>`).join(''); await nexaApi.saveSummary({ id: $('#editId').value || undefined, examId: $('#examSelect').value, title: $('#titleInput').value.trim(), introduction: $('#descriptionInput').value.trim(), content, contentType: type, pdfPath: savedPdfPath, pdfName: savedPdfName, authorId: user.id, status }); await render(); editor(false); } catch (error) { $('#studioMessage').textContent = error.message || 'Não foi possível salvar o resumo.'; } }
  document.addEventListener('click', async event => { const tab = event.target.closest('[data-view]'); if (tab) { editor(tab.dataset.view === 'editor'); if (tab.dataset.view === 'editor' && !$('#editId').value) reset(); } const button = event.target.closest('[data-action]'); if (!button) return; const summary = own().find(item => item.id === button.dataset.id); if (!summary) return; if (button.dataset.action === 'delete' && confirm('Excluir este resumo?')) { await nexaApi.deleteSummary(summary.id); await render(); } if (button.dataset.action === 'edit') { $('#editId').value = summary.id; $('#examSelect').value = summary.examId; $('#titleInput').value = summary.title; $('#descriptionInput').value = summary.introduction || ''; $('#formatSelect').value = summary.contentType || 'written'; $('#contentInput').value = (summary.content || '').replace(/<[^>]+>/g, '').trim(); savedPdfPath = summary.pdfPath; savedPdfName = summary.pdfName; pdfFile = null; $('#studioMessage').textContent = savedPdfName ? `PDF salvo: ${savedPdfName}` : ''; toggle(); editor(true); } });
  $('#formatSelect').onchange = toggle; $('#fileInput').onchange = event => { pdfFile = event.target.files[0] || null; if (pdfFile) $('#studioMessage').textContent = `PDF selecionado: ${pdfFile.name}`; }; $('#draftButton').onclick = () => save('draft'); $('#studioForm').onsubmit = event => { event.preventDefault(); save('published'); }; $('#logout').onclick = async () => { await authService.logout(); location.href = 'index.html'; };
  (async () => { user = await nexaApi.currentUser(); if (!user) { location.href = 'auth.html'; return; } await render(); editor(false); })();
  // Excluir publicações é uma ação administrativa; a regra do banco reforça essa proteção.
  const adminOnlyStyle = document.createElement('style'); adminOnlyStyle.textContent = '#mySummaryList [data-action="delete"]{display:none!important}'; document.head.append(adminOnlyStyle);
})();